SELECT * FROM TALUNO
WHERE NOME LIKE '%A%';

CREATE INDEX IND_TALUNO_NOME ON TALUNO(NOME);

CREATE INDEX IND_TALU_NOMECIDADE
ON TALUNO(NOME, CIDADE);

SELECT nome, cidade FROM TALUNO
WHERE NOME LIKE '%A%' AND CIDADE LIKE '%A%';


SELECT * FROM USER_INDEXES;

COMMIT;


