CREATE OR REPLACE VIEW V_ALUNO
AS
  SELECT COD_ALUNO AS CODIGO, NOME AS ALUNO, CIDADE
  FROM TALUNO;



  SELECT * FROM V_ALUNO
  ORDER BY ALUNO;



  CREATE OR REPLACE VIEW V_PESSOA_F
  AS
  SELECT COD_PESSOA, TIPO, NOME, COD_RUA AS RUA
  FROM TPESSOA
  WHERE TIPO='F';


  SELECT * FROM V_PESSOA_F;