CREATE SEQUENCE SEQ_ALUNO1
START WITH 60
INCREMENT BY 5
MINVALUE 60
MAXVALUE 100
NOCYCLE;


INSERT INTO TALUNO (cod_aluno, Nome)
VALUES (seq_aluno1.NEXTVAL, 'MASTER TRAINING');

INSERT INTO TALUNO (cod_aluno, Nome)
VALUES (seq_aluno1.NEXTVAL, 'MASTER TRAINING 2');

SELECT * FROM TALUNO;

SELECT * FROM USER_SEQUENCES;

--VALOR ATUAL
SELECT SEQ_ALUNO1.CURRVAL FROM DUAL;


ALTER SEQUENCE SEQ_ALUNO1
MAXVALUE 500;

COMMIT;

